service:
  env: "local"
  addr: ":8081"
db:
  driver: "mysql"
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "!980526Clb"
  database: "xiaomi_task1"
  charset: "utf8mb4"
  max_idle_conn: 10
  max_open_conn: 100
  enable_file_log_writer: true
  log_mode: "info"
  log_filename: "db.log"
log:
  level: "info"
  root_dir: "./logs"
  filename: "debug.log"
  format: "json"
  show_line: true
  max_backups: 3
  max_size: 500
  max_age: 365
  compress: true
